//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabayubak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestant
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Gender { get; set; }
        public string PhotoUrl { get; set; }
        public string ADDRESS { get; set; }
    }
}
