//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabayubak.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NabayubakDBEntities : DbContext
    {
        public NabayubakDBEntities()
            : base("name=NabayubakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contestant> Contestants { get; set; }
        public virtual DbSet<ContestantRating> ContestantRatings { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
        public virtual DbSet<SignUp> SignUp { get; set; }
        public virtual DbSet<Class_section_MAP> Class_section_MAP { get; set; }
        public virtual DbSet<Classname> Classname { get; set; }
        public virtual DbSet<Sectionname> Sectionname { get; set; }
    }
}
